### ISSUE TITLE
Package rxjs does not solve its peer dependencies!

### ISSUE THREAD

**Issue by rkistinger** [KallynGowdy/firebase-angular2-demo#5]
When I run an npm install I receive the error:

npm ERR! peerinvalid The package rxjs@5.0.0-beta.4 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.9 wants rxjs@5.0.0-beta.2

Please advise how to fix as I am new to npm dependencies. Thank you!

**Comment by KallynGowdy** [comment]
@rkistinger You should be able to run `npm uninstall rxjs` and `npm install rxjs --save` in the folder to fix the issue. Additionally, the errors should not cause an issue so long as the packages install.

**Comment by rkistinger** [comment]
Should I be running the npm commands from the 'ts' directory?

**Comment by rkistinger** [comment]
Thank you!
